//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeMadeFood.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeMadeFood.Web.App_GlobalResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходът трябва да е положително число.
        /// </summary>
        public static string CostMinValueErrorMessage {
            get {
                return ResourceManager.GetString("CostMinValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въдетете дата.
        /// </summary>
        public static string DateIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DateIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описанието е задължитело.
        /// </summary>
        public static string DescriptionIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описанието трябва да е с минимум 10 символа.
        /// </summary>
        public static string DescriptionMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типът на храната е задължителен.
        /// </summary>
        public static string FoodTypeIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("FoodTypeIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашна Храна.
        /// </summary>
        public static string HomeMadeFoodTitle {
            get {
                return ResourceManager.GetString("HomeMadeFoodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направи колегите си щастливи и им поръчай обяд!.
        /// </summary>
        public static string IndexMakeYourEmployeesHappy {
            get {
                return ResourceManager.GetString("IndexMakeYourEmployeesHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробвай.
        /// </summary>
        public static string IndexTryIt {
            get {
                return ResourceManager.GetString("IndexTryIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искаме  да направим деня в офиса ти по-радостен като се насладиш на вкусен, домашно приготвен обяд..
        /// </summary>
        public static string IndexWeAreHereToMakeYourDay {
            get {
                return ResourceManager.GetString("IndexWeAreHereToMakeYourDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количеството на съставка (за мерна единица) трябва да е положително число.
        /// </summary>
        public static string IngredientQuantityMinValueErrorMessage {
            get {
                return ResourceManager.GetString("IngredientQuantityMinValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция на рецептата е задължителна.
        /// </summary>
        public static string InstructionIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("InstructionIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция на рецептата трябва да е с минимум 10 символа.
        /// </summary>
        public static string InstructionMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("InstructionMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мерната единица е задължителна.
        /// </summary>
        public static string MeasuringUnitIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("MeasuringUnitIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името е задължитело.
        /// </summary>
        public static string NameIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името трябва да е с максимум 50 символа.
        /// </summary>
        public static string NameMaxValueErrorMessage {
            get {
                return ResourceManager.GetString("NameMaxValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името трябва да е с минимум 2 символа.
        /// </summary>
        public static string NameMinValueErrorMessage {
            get {
                return ResourceManager.GetString("NameMinValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчай обяд.
        /// </summary>
        public static string OrderYourLunchLink {
            get {
                return ResourceManager.GetString("OrderYourLunchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цената (за мерна единица) е задължителна.
        /// </summary>
        public static string PriceIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PriceIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цената (за мерна единица) трябва да е положително число.
        /// </summary>
        public static string PriceMinValueErrorMessage {
            get {
                return ResourceManager.GetString("PriceMinValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количестото трябва да е положително число.
        /// </summary>
        public static string QuantityMinValueErrorMessage {
            get {
                return ResourceManager.GetString("QuantityMinValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай се.
        /// </summary>
        public static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието е задължитело.
        /// </summary>
        public static string TitleIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("TitleIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието трябва да е с максимум 50 символа.
        /// </summary>
        public static string TitleMaxValueErrorMessage {
            get {
                return ResourceManager.GetString("TitleMaxValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието трябва да е с минимум 2 символа.
        /// </summary>
        public static string TitleMinValueErrorMessage {
            get {
                return ResourceManager.GetString("TitleMinValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневно меню за {0:dd/MM/yyyy} не успя да се добави. Моля, проверете отново входните данни. Благодаря!.
        /// </summary>
        public static string ToastrAddDailyMenuFailureMessage {
            get {
                return ResourceManager.GetString("ToastrAddDailyMenuFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно добавихте дневно меню за {0:dd/MM/yyyy}.
        /// </summary>
        public static string ToastrAddDailyMenuSuccessMessage {
            get {
                return ResourceManager.GetString("ToastrAddDailyMenuSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не успя да се добави. Моля, проверете отново входните данни. Благодаря!.
        /// </summary>
        public static string ToastrAddObjectFailureMessage {
            get {
                return ResourceManager.GetString("ToastrAddObjectFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавихте успешно {0}..
        /// </summary>
        public static string ToastrAddObjectSuccessMessage {
            get {
                return ResourceManager.GetString("ToastrAddObjectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневно меню за {0:dd/MM/yyyy} не успя да сe премахне..
        /// </summary>
        public static string ToastrDeleteDailyMenuFailureMessage {
            get {
                return ResourceManager.GetString("ToastrDeleteDailyMenuFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно премахнахте дневно меню за {0:dd/MM/yyyy}.
        /// </summary>
        public static string ToastrDeleteDailyMenuSuccessMessage {
            get {
                return ResourceManager.GetString("ToastrDeleteDailyMenuSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не успя да сe премахне..
        /// </summary>
        public static string ToastrDeleteObjectFailureMessage {
            get {
                return ResourceManager.GetString("ToastrDeleteObjectFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахнахте успешно {0}..
        /// </summary>
        public static string ToastrDeleteObjectSuccessMessage {
            get {
                return ResourceManager.GetString("ToastrDeleteObjectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нещо не е наред....
        /// </summary>
        public static string ToastrFailureTitle {
            get {
                return ResourceManager.GetString("ToastrFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневно меню за {0:dd/MM/yyyy} не успя да сe редактира. Моля, проверете отново входните данни. Благодаря!.
        /// </summary>
        public static string ToastrUpdateDailyMenuFailureMessage {
            get {
                return ResourceManager.GetString("ToastrUpdateDailyMenuFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не успя да сe редактира. Моля, проверете отново входните данни. Благодаря!.
        /// </summary>
        public static string ToastrUpdateObjectFailureMessage {
            get {
                return ResourceManager.GetString("ToastrUpdateObjectFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирахте успешно {0}..
        /// </summary>
        public static string ToastrUpdateObjectSuccessMessage {
            get {
                return ResourceManager.GetString("ToastrUpdateObjectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех!.
        /// </summary>
        public static string ТoastrSuccessTitle {
            get {
                return ResourceManager.GetString("ТoastrSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно редактирахте дневно меню за {0:dd/MM/yyyy}.
        /// </summary>
        public static string ТoastrUpdateDailyMenuSuccessMessage {
            get {
                return ResourceManager.GetString("ТoastrUpdateDailyMenuSuccessMessage", resourceCulture);
            }
        }
    }
}
