// <auto-generated />
namespace HomeMadeFood.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RecipesUpdatedWithNewModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecipesUpdatedWithNewModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201703191758458_RecipesUpdatedWithNewModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
